all: form_view_style template_style
form_view_style:
	sass ./template/form_page_template/styles.scss ./template/form_page_template/styles.css
template_style:
	sass ./template/avg_page_template/template_styles.scss ./template/avg_page_template/styles.css